# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ds_service_client import ds_service_pb2 as ds__service__client_dot_ds__service__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ds_service_client/ds_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MapSet = channel.unary_unary(
                '/DsService/MapSet',
                request_serializer=ds__service__client_dot_ds__service__pb2.MapSetRequest.SerializeToString,
                response_deserializer=ds__service__client_dot_ds__service__pb2.Empty.FromString,
                _registered_method=True)
        self.MapGet = channel.unary_unary(
                '/DsService/MapGet',
                request_serializer=ds__service__client_dot_ds__service__pb2.MapGetRequest.SerializeToString,
                response_deserializer=ds__service__client_dot_ds__service__pb2.MapGetResponse.FromString,
                _registered_method=True)
        self.MapSearchKey = channel.unary_unary(
                '/DsService/MapSearchKey',
                request_serializer=ds__service__client_dot_ds__service__pb2.MapSearchKeyRequest.SerializeToString,
                response_deserializer=ds__service__client_dot_ds__service__pb2.MapSearchKeyResponse.FromString,
                _registered_method=True)
        self.TaskAdd = channel.unary_unary(
                '/DsService/TaskAdd',
                request_serializer=ds__service__client_dot_ds__service__pb2.TaskAddRequest.SerializeToString,
                response_deserializer=ds__service__client_dot_ds__service__pb2.Empty.FromString,
                _registered_method=True)
        self.TaskStatus = channel.unary_unary(
                '/DsService/TaskStatus',
                request_serializer=ds__service__client_dot_ds__service__pb2.TaskStatusRequest.SerializeToString,
                response_deserializer=ds__service__client_dot_ds__service__pb2.TaskStatusResponse.FromString,
                _registered_method=True)
        self.TaskGet = channel.unary_unary(
                '/DsService/TaskGet',
                request_serializer=ds__service__client_dot_ds__service__pb2.TaskGetRequest.SerializeToString,
                response_deserializer=ds__service__client_dot_ds__service__pb2.TaskGetResponse.FromString,
                _registered_method=True)
        self.TaskDone = channel.unary_unary(
                '/DsService/TaskDone',
                request_serializer=ds__service__client_dot_ds__service__pb2.TaskDoneRequest.SerializeToString,
                response_deserializer=ds__service__client_dot_ds__service__pb2.Empty.FromString,
                _registered_method=True)
        self.Requeue = channel.unary_unary(
                '/DsService/Requeue',
                request_serializer=ds__service__client_dot_ds__service__pb2.RequeueRequest.SerializeToString,
                response_deserializer=ds__service__client_dot_ds__service__pb2.Empty.FromString,
                _registered_method=True)
        self.JournalSize = channel.unary_unary(
                '/DsService/JournalSize',
                request_serializer=ds__service__client_dot_ds__service__pb2.JournalSizeRequest.SerializeToString,
                response_deserializer=ds__service__client_dot_ds__service__pb2.JournalSizeResponse.FromString,
                _registered_method=True)
        self.JournalRead = channel.unary_unary(
                '/DsService/JournalRead',
                request_serializer=ds__service__client_dot_ds__service__pb2.JournalReadRequest.SerializeToString,
                response_deserializer=ds__service__client_dot_ds__service__pb2.JournalReadResponse.FromString,
                _registered_method=True)
        self.JournalAppend = channel.unary_unary(
                '/DsService/JournalAppend',
                request_serializer=ds__service__client_dot_ds__service__pb2.JournalAppendRequest.SerializeToString,
                response_deserializer=ds__service__client_dot_ds__service__pb2.Empty.FromString,
                _registered_method=True)


class DsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MapSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MapGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MapSearchKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskAdd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskDone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Requeue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JournalSize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JournalRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JournalAppend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MapSet': grpc.unary_unary_rpc_method_handler(
                    servicer.MapSet,
                    request_deserializer=ds__service__client_dot_ds__service__pb2.MapSetRequest.FromString,
                    response_serializer=ds__service__client_dot_ds__service__pb2.Empty.SerializeToString,
            ),
            'MapGet': grpc.unary_unary_rpc_method_handler(
                    servicer.MapGet,
                    request_deserializer=ds__service__client_dot_ds__service__pb2.MapGetRequest.FromString,
                    response_serializer=ds__service__client_dot_ds__service__pb2.MapGetResponse.SerializeToString,
            ),
            'MapSearchKey': grpc.unary_unary_rpc_method_handler(
                    servicer.MapSearchKey,
                    request_deserializer=ds__service__client_dot_ds__service__pb2.MapSearchKeyRequest.FromString,
                    response_serializer=ds__service__client_dot_ds__service__pb2.MapSearchKeyResponse.SerializeToString,
            ),
            'TaskAdd': grpc.unary_unary_rpc_method_handler(
                    servicer.TaskAdd,
                    request_deserializer=ds__service__client_dot_ds__service__pb2.TaskAddRequest.FromString,
                    response_serializer=ds__service__client_dot_ds__service__pb2.Empty.SerializeToString,
            ),
            'TaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.TaskStatus,
                    request_deserializer=ds__service__client_dot_ds__service__pb2.TaskStatusRequest.FromString,
                    response_serializer=ds__service__client_dot_ds__service__pb2.TaskStatusResponse.SerializeToString,
            ),
            'TaskGet': grpc.unary_unary_rpc_method_handler(
                    servicer.TaskGet,
                    request_deserializer=ds__service__client_dot_ds__service__pb2.TaskGetRequest.FromString,
                    response_serializer=ds__service__client_dot_ds__service__pb2.TaskGetResponse.SerializeToString,
            ),
            'TaskDone': grpc.unary_unary_rpc_method_handler(
                    servicer.TaskDone,
                    request_deserializer=ds__service__client_dot_ds__service__pb2.TaskDoneRequest.FromString,
                    response_serializer=ds__service__client_dot_ds__service__pb2.Empty.SerializeToString,
            ),
            'Requeue': grpc.unary_unary_rpc_method_handler(
                    servicer.Requeue,
                    request_deserializer=ds__service__client_dot_ds__service__pb2.RequeueRequest.FromString,
                    response_serializer=ds__service__client_dot_ds__service__pb2.Empty.SerializeToString,
            ),
            'JournalSize': grpc.unary_unary_rpc_method_handler(
                    servicer.JournalSize,
                    request_deserializer=ds__service__client_dot_ds__service__pb2.JournalSizeRequest.FromString,
                    response_serializer=ds__service__client_dot_ds__service__pb2.JournalSizeResponse.SerializeToString,
            ),
            'JournalRead': grpc.unary_unary_rpc_method_handler(
                    servicer.JournalRead,
                    request_deserializer=ds__service__client_dot_ds__service__pb2.JournalReadRequest.FromString,
                    response_serializer=ds__service__client_dot_ds__service__pb2.JournalReadResponse.SerializeToString,
            ),
            'JournalAppend': grpc.unary_unary_rpc_method_handler(
                    servicer.JournalAppend,
                    request_deserializer=ds__service__client_dot_ds__service__pb2.JournalAppendRequest.FromString,
                    response_serializer=ds__service__client_dot_ds__service__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MapSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DsService/MapSet',
            ds__service__client_dot_ds__service__pb2.MapSetRequest.SerializeToString,
            ds__service__client_dot_ds__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MapGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DsService/MapGet',
            ds__service__client_dot_ds__service__pb2.MapGetRequest.SerializeToString,
            ds__service__client_dot_ds__service__pb2.MapGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MapSearchKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DsService/MapSearchKey',
            ds__service__client_dot_ds__service__pb2.MapSearchKeyRequest.SerializeToString,
            ds__service__client_dot_ds__service__pb2.MapSearchKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TaskAdd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DsService/TaskAdd',
            ds__service__client_dot_ds__service__pb2.TaskAddRequest.SerializeToString,
            ds__service__client_dot_ds__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DsService/TaskStatus',
            ds__service__client_dot_ds__service__pb2.TaskStatusRequest.SerializeToString,
            ds__service__client_dot_ds__service__pb2.TaskStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TaskGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DsService/TaskGet',
            ds__service__client_dot_ds__service__pb2.TaskGetRequest.SerializeToString,
            ds__service__client_dot_ds__service__pb2.TaskGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TaskDone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DsService/TaskDone',
            ds__service__client_dot_ds__service__pb2.TaskDoneRequest.SerializeToString,
            ds__service__client_dot_ds__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Requeue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DsService/Requeue',
            ds__service__client_dot_ds__service__pb2.RequeueRequest.SerializeToString,
            ds__service__client_dot_ds__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JournalSize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DsService/JournalSize',
            ds__service__client_dot_ds__service__pb2.JournalSizeRequest.SerializeToString,
            ds__service__client_dot_ds__service__pb2.JournalSizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JournalRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DsService/JournalRead',
            ds__service__client_dot_ds__service__pb2.JournalReadRequest.SerializeToString,
            ds__service__client_dot_ds__service__pb2.JournalReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JournalAppend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DsService/JournalAppend',
            ds__service__client_dot_ds__service__pb2.JournalAppendRequest.SerializeToString,
            ds__service__client_dot_ds__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
